name: llama_ui
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip

  - pip:
      - torch==2.11.0
      - transformers==5.5.4
      - sentence-transformers==5.4.1
      - spacy==3.8.14
      - numpy==2.2.6
      - scipy==1.15.3
      - opencv-python==4.13.0.92
      - pillow==12.2.0
      - requests==2.32.5
      - huggingface_hub==1.11.0
      - tokenizers==0.22.2
      - tqdm==4.67.3
      - scikit-learn==1.7.2
      - triton==3.6.0
